# Timeout in seconds that Limine will use before automatically booting.
timeout: 5

/ViceOS
    protocol: limine
    path: boot():/boot/vice.elf

    module_path: boot():/vicetek.rgb
    module_cmdline: FILE
